# Setup
title:            CR4-DL
tagline:          'In search of that which is true.'
description:      'The Cradle. A vault for notes on artificial intelligence and the brain.'
url:              https://brianpho.com
baseurl:          # does not include hostname
       
# Filtering Content
show_drafts:      null
limit_posts:      0
future:           true
unpublished:      false      

# Plugins
whitelist:        []
plugins:          [jekyll-gist, jekyll-paginate]

# Conversion
markdown:         kramdown
highlighter:      rouge

# Outputting
permalink:        date
paginate:         5
paginate_path:    /page:num
timezone:         null

quiet:            false
verbose:          false
defaults:         []

# Custom vars
sidebar_home_link:  true
github:
  repo: https://github.com/Brian-Pho/CR4-DL
