# Setup
title:            CR4-DL
tagline:          'The Cradle.'
description:      'The Cradle. A vault for notes on artificial intelligence and the brain.'
url:              https://brianpho.com
baseurl:          # does not include hostname
author:           Brian Pho

# Filtering Content
show_drafts:      null
limit_posts:      0
future:           false
unpublished:      false

# Social Media
github:
  username:       Brian-Pho

social:
  name:           Brian Pho
  links:
    - https://brianpho.com
    - https://github.com/username
    - https://www.facebook.com/username
    - https://www.linkedin.com/in/username

# Outputting
first_run:        2018
toc:              true
paginate:         10
timezone:         null

quiet:            false
verbose:          false
defaults:         []

# Conversion
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Home
          url: /
  -
    scope:
      path: assets/data
    values:


sass:
  sass_dir: /assets/css
  style: compressed

exclude:
  - Gemfile.lock
  - Gemfile
  - docs

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /posts/
    - 404.html
    - sitemap.xml
    - robots.txt
    - redirects.json
